/*
 * ncgb: This was my degree thesis project. It consist of a library for
 * computing Gröbner basis in the free algebra.
 */

extern "C" {
#include <gap_all.h>    // GAP headers
}

#include <bits/stdc++.h>
#include <cstdio>
#include <cstring>    // Para memcpy
#include <gmpxx.h>
#include <sstream>    // Agrega esta línea al inicio del archivo
#include <string>     // Para memcpy

#include "ncgb/Buchberger.hpp"

using namespace std;
using namespace ncgb;
#include "ncgb/F4.hpp"
#include <flint/fmpq.h>
#include <flint/fmpq_mat.h>


typedef Poly<mpq_class> P;


typedef mpq_class R;
typedef Poly<R> PM;

// int Prueba(size_t n) {

//   size_t n;
//   cin >> n;
//   vector<PM> G(n);
//   for (size_t i = 0; i < n; ++i) {
//     cin >> G[i];
//   }

  
//   cout << base.size() << endl;
//   for (auto f : base) {
//     f.nice_print();
//   }
// }


Obj FuncFalopa4(Obj self, Obj listGenG)
{
    // Verificar que listGenG es una lista válida
    if (!IS_PLIST(listGenG)) {
        ErrorMayQuit("InIdeal_BuchbergerCofactor: Se esperaba una lista de polinomios.", 0, 0);
        return Fail;
    }
    const char* response;

    // Obtener el número de generadores
    Int numGen = LEN_LIST(listGenG);
    if (numGen == 0) {
        ErrorMayQuit("InIdeal_BuchbergerCofactor: La lista de generadores está vacía.", 0, 0);
        return Fail;
    }

    // Convertir `listGenG` a un vector de polinomios `std::vector<P>`
    std::vector<PM> G(numGen);
    for (Int i = 1; i <= numGen; i++) {
        const char* polyStr = CSTR_STRING(ELM_LIST(listGenG, i));
        // Convierte la cadena en un flujo de entrada
        std::istringstream iss(polyStr);
        // Pasa el flujo a nice_read
        G[i - 1] = P::nice_read(iss);
        G[i -1].nice_print();
    }

    // F4Incremental F4(G);

    // vector<PM> base = F4.fullBase();
    //  cout << base.size() << endl;
    // for (auto f : base) {
    //     // response.append(f.nice_print))
    //     f.nice_print();
    // }

    // Ejecutar el algoritmo de Buchberger
    // auto [ims, corep] = inIdealCofactor(G, polyF, k);

    // Crear objeto GAP para la respuesta
    
    response = "Hola";
    Int len = strlen(response);
    Obj result = NEW_STRING(len);
    memcpy(CSTR_STRING(result), response, len);

    return result;
}

/*
Obj FuncFalopa4(Obj self, Obj listGenG)
{
    if (!IS_PLIST(listGenG)) {
        ErrorMayQuit("Falopa4: Se esperaba una lista.", 0, 0);
        return Fail;
    }

    Int numGen = LEN_LIST(listGenG);
    if (numGen == 0) {
        ErrorMayQuit("Falopa4: La lista está vacía.", 0, 0);
        return Fail;
    }

    std::vector<PM> G(numGen);

    for (Int i = 1; i <= numGen; i++) {
        const char *polyStr = CSTR_STRING(ELM_LIST(listGenG, i));
        std::istringstream iss(polyStr);
        G[i - 1] = P::nice_read(iss);
    }

    Obj result = NEW_PLIST(T_PLIST, numGen);
    SET_LEN_PLIST(result, numGen);

    for (Int i = 0; i < numGen; i++) {

        std::ostringstream out;
        G[i].nice_print(out);

        std::string s = out.str();

        Obj str = MakeString(s.c_str());

        SET_ELM_PLIST(result, i + 1, str);
    }

    CHANGED_BAG(result);

    return result;
}
*/

Obj FuncTestCommand(Obj self)
{
    return INTOBJ_INT(42);
}

Obj FuncTestCommandWithParams(Obj self, Obj param, Obj param2)
{
    /* simply return the first parameter */
    return param;
}

/**
 * Function that wraps the Buchberger algorithm to check if a polynomial
 * belongs to the ideal generated by a list of polynomials, with a maximum
 * number of steps.
 */

Obj FuncPolynomialString(Obj self, Obj poly, Obj steps)
{
    // Obtener la cadena en formato C
    const char * cstr = CSTR_STRING(poly);
    Int          len = strlen(cstr);    // Obtener la longitud de la cadena

    // Crear un nuevo objeto GAP para la cadena resultante
    Obj gapStr = NEW_STRING(len);

    // Copiar el contenido de cstr al objeto GAP
    memcpy(CSTR_STRING(gapStr), cstr, len);

    return gapStr;
}

Obj FuncModifyPolynomialString(Obj self, Obj poly, Obj steps)
{
    // Obtener la cadena en formato C
    const char * cstr = CSTR_STRING(poly);
    Int          len = strlen(cstr);    // Obtener la longitud de la cadena

    // Crear la nueva cadena modificada
    std::string nuevaCadena = std::string(cstr) + "_modificado";

    Int newLen = nuevaCadena.length();    // Longitud de la nueva cadena

    // Crear un nuevo objeto GAP con la longitud adecuada
    Obj newGapStr = NEW_STRING(newLen);

    // Copiar la nuevaCadena al objeto GAP
    memcpy(CSTR_STRING(newGapStr), nuevaCadena.c_str(), newLen);

    return newGapStr;
}

Obj FuncGetFirstPolynomial(Obj self, Obj ListPoly, Obj steps)
{
    // Verificar que el argumento es una lista válida
    if (!IS_LIST(ListPoly)) {
        ErrorMayQuit("GetFirstPolynomial: Se esperaba una lista como argumento.", 0, 0);
        return Fail;
    }

    // Obtener el primer elemento de la lista
    if (LEN_LIST(ListPoly) < 1) {
        ErrorMayQuit("GetFirstPolynomial: La lista está vacía.", 0, 0);
        return Fail;
    }

    return ELM_LIST(ListPoly, 1);
}

Obj FuncInIdeal_BuchbergerCofactor(Obj self, Obj f, Obj listGenG, Obj steps)
{
    // Verificar que listGenG es una lista válida
    if (!IS_PLIST(listGenG)) {
        ErrorMayQuit("InIdeal_BuchbergerCofactor: Se esperaba una lista de polinomios.", 0, 0);
        return Fail;
    }

    // Verificar que steps es un entero
    if (!IS_INTOBJ(steps)) {
        ErrorMayQuit("InIdeal_BuchbergerCofactor: Se esperaba un número entero de pasos.", 0, 0);
        return Fail;
    }

    // Obtener el número de generadores
    Int numGen = LEN_LIST(listGenG);
    if (numGen == 0) {
        ErrorMayQuit("InIdeal_BuchbergerCofactor: La lista de generadores está vacía.", 0, 0);
        return Fail;
    }

    // Convertir `listGenG` a un vector de polinomios `std::vector<P>`
    std::vector<P> G(numGen);
    for (Int i = 1; i <= numGen; i++) {
        const char* polyStr = CSTR_STRING(ELM_LIST(listGenG, i));
        // Convierte la cadena en un flujo de entrada
        std::istringstream iss(polyStr);
        // Pasa el flujo a nice_read
        G[i - 1] = P::nice_read(iss);
    }

    // Convertir `f` a un polinomio `P`
    const char* polyFcstr = CSTR_STRING(f);
    std::istringstream isss(polyFcstr);
    P polyF = P::nice_read(isss);

    // Convertir `steps` a un número entero C++
    size_t k = INT_INTOBJ(steps);
    k += G.size(); // Como en el código original

    // Ejecutar el algoritmo de Buchberger
    auto [ims, corep] = inIdealCofactor(G, polyF, k);

    // Crear objeto GAP para la respuesta
    const char* response;

    // Convertir n de Obj a un entero C
    //Int nn = INT_INTOBJ(n);
    if (ims == InIdeal) {
        response = "InIdeal";
    }
    else if (ims == NotInIdeal) {
        response = "NotInIdeal";
    }
    else {
        response = "Unknown";
    }

    Int len = strlen(response);
    Obj result = NEW_STRING(len);
    memcpy(CSTR_STRING(result), response, len);

    return result;
}


// Table of functions to export
static StructGVarFunc GVarFuncs[] = {
    GVAR_FUNC(TestCommand, 0, ""),
    GVAR_FUNC(TestCommandWithParams, 2, "param, param2"),
    GVAR_FUNC(PolynomialString, 2, "poly, steps"),
    GVAR_FUNC(ModifyPolynomialString, 2, "poly, steps"),
    GVAR_FUNC(GetFirstPolynomial, 2, "ListPoly, steps"),
    GVAR_FUNC(InIdeal_BuchbergerCofactor, 3, "poly, listGenG, steps"),
    GVAR_FUNC(Falopa4, 1, "listGenG"),

    { 0 } /* Finish with an empty entry */
};

/****************************************************************************
**
*F  InitKernel( <module> ) . . . . . . . .  initialise kernel data structures
*/
static Int InitKernel(StructInitInfo * module)
{
    /* init filters and functions */
    InitHdlrFuncsFromTable(GVarFuncs);

    /* return success */
    return 0;
}

/****************************************************************************
**
*F  InitLibrary( <module> ) . . . . . . .  initialise library data structures
*/
static Int InitLibrary(StructInitInfo * module)
{
    /* init filters and functions */
    InitGVarFuncsFromTable(GVarFuncs);

    /* return success */
    return 0;
}

/****************************************************************************
**
*F  Init__Dynamic() . . . . . . . . . . . . . . . . . table of init functions
*/
static StructInitInfo module = {
    /* type        = */ MODULE_DYNAMIC,
    /* name        = */ "ncgb",
    /* revision_c  = */ 0,
    /* revision_h  = */ 0,
    /* version     = */ 0,
    /* crc         = */ 0,
    /* initKernel  = */ InitKernel,
    /* initLibrary = */ InitLibrary,
    /* checkInit   = */ 0,
    /* preSave     = */ 0,
    /* postSave    = */ 0,
    /* postRestore = */ 0,
    /* moduleStateSize      = */ 0,
    /* moduleStateOffsetPtr = */ 0,
    /* initModuleState      = */ 0,
    /* destroyModuleState   = */ 0,
};

extern "C" StructInitInfo * Init__Dynamic(void)
{
    return &module;
}
